services:
  backend:
    build:
      context: tasintausif/distributionmanagementsystem-backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/var/www/html
      - backend_vendor:/var/www/html/vendor
    depends_on:
      - db

  frontend:
    build:
      context: .tasintausif/distributionmanagementsystem-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  db:
    image: mysql:8.0
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

  backend_vendor:
